// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/ClientAction.proto

package message.core;

public final class ClientActionProto {
  private ClientActionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code message.core.ClientAction}
   *
   * <pre>
   *客户端请求命令列表
   * </pre>
   */
  public enum ClientAction
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ACTION_HEARTBEAT = 1;</code>
     *
     * <pre>
     *心跳;
     * </pre>
     */
    ACTION_HEARTBEAT(0, 1),
    /**
     * <code>ACTION_LOGIN = 2;</code>
     *
     * <pre>
     *登录;
     * </pre>
     */
    ACTION_LOGIN(1, 2),
    ;

    /**
     * <code>ACTION_HEARTBEAT = 1;</code>
     *
     * <pre>
     *心跳;
     * </pre>
     */
    public static final int ACTION_HEARTBEAT_VALUE = 1;
    /**
     * <code>ACTION_LOGIN = 2;</code>
     *
     * <pre>
     *登录;
     * </pre>
     */
    public static final int ACTION_LOGIN_VALUE = 2;


    public final int getNumber() { return value; }

    public static ClientAction valueOf(int value) {
      switch (value) {
        case 1: return ACTION_HEARTBEAT;
        case 2: return ACTION_LOGIN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ClientAction>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ClientAction>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ClientAction>() {
            public ClientAction findValueByNumber(int number) {
              return ClientAction.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return message.core.ClientActionProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final ClientAction[] VALUES = values();

    public static ClientAction valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ClientAction(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:message.core.ClientAction)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027core/ClientAction.proto\022\014message.core*" +
      "6\n\014ClientAction\022\024\n\020ACTION_HEARTBEAT\020\001\022\020\n" +
      "\014ACTION_LOGIN\020\002B\023B\021ClientActionProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
