// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/PushMsg.proto

package message.core;

public final class PushMsgProto {
  private PushMsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code message.core.PushType}
   *
   * <pre>
   * 推送数据类型
   * </pre>
   */
  public enum PushType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PUSH_PLAYER = 1;</code>
     *
     * <pre>
     *玩家数据
     * </pre>
     */
    PUSH_PLAYER(0, 1),
    ;

    /**
     * <code>PUSH_PLAYER = 1;</code>
     *
     * <pre>
     *玩家数据
     * </pre>
     */
    public static final int PUSH_PLAYER_VALUE = 1;


    public final int getNumber() { return value; }

    public static PushType valueOf(int value) {
      switch (value) {
        case 1: return PUSH_PLAYER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PushType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<PushType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PushType>() {
            public PushType findValueByNumber(int number) {
              return PushType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return message.core.PushMsgProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final PushType[] VALUES = values();

    public static PushType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private PushType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:message.core.PushType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022core/PushMsg.proto\022\014message.core*\033\n\010Pu" +
      "shType\022\017\n\013PUSH_PLAYER\020\001B\016B\014PushMsgProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
